// Split a comma-separated tag string into trimmed, non-empty, case-insensitively
// unique tags (keeping the first spelling seen). Used so a prompt can never hold
// the same tag twice.
export function dedupeTags(raw: string | null | undefined): string[] {
  const seen = new Set<string>()
  const out: string[] = []
  for (const part of (raw ?? '').split(',')) {
    const t = part.trim()
    const key = t.toLowerCase()
    if (t && !seen.has(key)) {
      seen.add(key)
      out.push(t)
    }
  }
  return out
}

// Normalize a tag field to a deduped, comma-separated string.
export function normalizeTags(raw: string | null | undefined): string {
  return dedupeTags(raw).join(', ')
}

// ---- Suggestion ranking (central vocabulary + curated catalogue) ----------

/** One entry of the autocomplete pool. */
export interface TagSuggestion {
  name: string
  /** How many prompts carry it (0 for catalogue entries not yet used). */
  usage: number
  /** Where it comes from — shown as a hint in the menu. */
  source: 'user' | 'system' | 'catalog'
  /** Epoch ms of the last use; breaks ties in favour of recent work. */
  lastUsed?: number
}

/**
 * Merge the saved vocabulary with the curated catalogue.
 *
 * Saved tags win: a catalogue word that the user already uses keeps its usage
 * count and provenance instead of being listed twice.
 */
export function mergeSuggestionPool(
  saved: TagSuggestion[],
  catalog: readonly string[] = DEV_TAGS,
): TagSuggestion[] {
  const out: TagSuggestion[] = []
  const seen = new Set<string>()
  for (const entry of saved) {
    const key = entry.name.trim().toLowerCase()
    if (!key || seen.has(key)) continue
    seen.add(key)
    out.push(entry)
  }
  for (const name of catalog) {
    const key = name.toLowerCase()
    if (seen.has(key)) continue
    seen.add(key)
    out.push({ name, usage: 0, source: 'catalog' })
  }
  return out
}

/** Match quality of a candidate against the typed query (lower = better). */
function matchRank(name: string, query: string): number {
  if (!query) return 3
  const lower = name.toLowerCase()
  if (lower === query) return 0
  if (lower.startsWith(query)) return 1
  // Start of a word inside the tag ("dark-mode" for "mode").
  if (new RegExp(`[-_ /]${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`).test(lower)) return 2
  return lower.includes(query) ? 3 : -1
}

/** Why a suggestion was pushed up — shown as a hint in the menu. */
export type SuggestReason = 'title' | 'related'

export interface RankedSuggestion extends TagSuggestion {
  reason?: SuggestReason
}

/**
 * What the prompt being written implies, independent of the typed fragment.
 *
 * `derived` comes from the title (see lib/tag-rules.ts), `related` from tags
 * that co-occur with the ones already picked. Both are measured signals: given
 * `enhancement`, the tag `feature` follows in 42 % of prompts against a 22 %
 * base rate; given `feature`, `improvement` follows in 41 % against 41 %… which
 * is why co-occurrence only breaks ties and never outranks what was typed.
 */
export interface RankContext {
  derived?: ReadonlySet<string>
  related?: ReadonlySet<string>
}

/** 2 = the title says so, 1 = it goes with what is already chosen, 0 = neither. */
function contextScore(name: string, context: RankContext | undefined): number {
  if (!context) return 0
  const key = name.toLowerCase()
  if (context.derived?.has(key)) return 2
  if (context.related?.has(key)) return 1
  return 0
}

/**
 * Rank suggestions for the typed fragment.
 *
 * Order: match quality, then context, then how often the tag is used, then how
 * recently, then alphabetically — so the vocabulary a user actually works with
 * floats up while the catalogue stays reachable for partial matches.
 *
 * Match quality stays FIRST on purpose: typing "sec" must offer `security`,
 * however strongly the title suggests something else. Context only decides
 * between candidates the query ranks equally — which, with an empty query, is
 * all of them, and that is exactly the moment the menu has nothing else to go on.
 */
export function rankSuggestions(
  pool: TagSuggestion[],
  rawQuery: string,
  {
    exclude = new Set<string>(),
    limit = 8,
    context,
  }: { exclude?: Set<string>; limit?: number; context?: RankContext } = {},
): RankedSuggestion[] {
  const query = rawQuery.trim().toLowerCase()
  const scored: { entry: TagSuggestion; rank: number; ctx: number }[] = []
  for (const entry of pool) {
    const key = entry.name.toLowerCase()
    if (exclude.has(key)) continue
    const rank = matchRank(entry.name, query)
    if (rank < 0) continue
    scored.push({ entry, rank, ctx: contextScore(entry.name, context) })
  }
  scored.sort((a, b) => {
    if (a.rank !== b.rank) return a.rank - b.rank
    if (a.ctx !== b.ctx) return b.ctx - a.ctx
    if (a.entry.usage !== b.entry.usage) return b.entry.usage - a.entry.usage
    const recency = (b.entry.lastUsed ?? 0) - (a.entry.lastUsed ?? 0)
    if (recency !== 0) return recency
    return a.entry.name.localeCompare(b.entry.name)
  })
  return scored.slice(0, limit).map((s) => ({
    ...s.entry,
    reason: s.ctx === 2 ? ('title' as const) : s.ctx === 1 ? ('related' as const) : undefined,
  }))
}

/**
 * Tags that travel with the ones already chosen, most frequent first.
 *
 * Built from the prompts the client already holds — no extra request, and it
 * stays current with every optimistic update.
 */
export function relatedTags(
  prompts: readonly { tags: string }[],
  chosen: Iterable<string>,
  limit = 6,
): Set<string> {
  const picked = new Set([...chosen].map((t) => t.trim().toLowerCase()).filter(Boolean))
  if (!picked.size) return new Set()
  const counts = new Map<string, number>()
  for (const prompt of prompts) {
    const tags = dedupeTags(prompt.tags).map((t) => t.toLowerCase())
    if (!tags.some((t) => picked.has(t))) continue
    for (const tag of tags) {
      if (picked.has(tag)) continue
      counts.set(tag, (counts.get(tag) ?? 0) + 1)
    }
  }
  return new Set(
    [...counts.entries()]
      .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
      .slice(0, limit)
      .map(([tag]) => tag),
  )
}

// Curated English software-development tags suggested in the tag autocomplete.
// Kept lowercase, single-token (use hyphens, no spaces) so they round-trip
// cleanly through the comma-separated tag field.
export const DEV_TAGS: string[] = [
  // change type
  'feature',
  'enhancement',
  'improvement',
  'bug',
  'fix',
  'bugfix',
  'hotfix',
  'quickfix',
  'workaround',
  'regression',
  'refactor',
  'cleanup',
  'chore',
  'tech-debt',
  'breaking-change',
  'revert',
  // work state / priority
  'wip',
  'blocked',
  'urgent',
  'high-priority',
  'low-priority',
  'idea',
  'research',
  'spike',
  'prototype',
  'mvp',
  'experimental',
  'polish',
  'review',
  'question',
  'duplicate',
  'wontfix',
  // layers / areas
  'frontend',
  'backend',
  'fullstack',
  'api',
  'database',
  'ui',
  'ux',
  'design',
  'infra',
  'devops',
  'tooling',
  'config',
  'dependencies',
  // disciplines
  'security',
  'performance',
  'accessibility',
  'i18n',
  'l10n',
  'seo',
  'testing',
  'unit-test',
  'integration-test',
  'e2e',
  'documentation',
  'logging',
  'monitoring',
  'analytics',
  'error-handling',
  'validation',
  'caching',
  'optimization',
  'migration',
  // delivery
  'build',
  'ci',
  'cd',
  'deploy',
  'release',
  'docker',
  'automation',
  // platforms
  'web',
  'mobile',
  'desktop',
  'pwa',
  // tech
  'typescript',
  'python',
  'rust',
  'go',
  'react',
  'sql',
  'graphql',
  'websocket',
  'styling',
  'animation',
  'responsive',
  // ui components & patterns
  'gui',
  'layout',
  'grid',
  'flexbox',
  'modal',
  'dialog',
  'tooltip',
  'dropdown',
  'menu',
  'navigation',
  'sidebar',
  'header',
  'footer',
  'form',
  'input',
  'button',
  'icon',
  'card',
  'table',
  'list-view',
  'pagination',
  'infinite-scroll',
  'virtualization',
  'carousel',
  'tabs',
  'accordion',
  'stepper',
  'wizard',
  'breadcrumb',
  'autocomplete',
  'datepicker',
  'slider',
  'toggle',
  'checkbox',
  'radio',
  'select-field',
  'textarea',
  'badge',
  'avatar',
  'chip',
  'banner',
  'toast',
  'snackbar',
  'notification',
  'popover',
  'context-menu',
  'drawer',
  'overlay',
  'lightbox',
  'empty-state',
  'skeleton',
  'spinner',
  'progress-bar',
  'placeholder',
  'fab',
  'app-bar',
  'bottom-sheet',
  'split-view',
  'masonry',
  'sticky',
  'scrollbar',
  // ux & interaction
  'transition',
  'micro-interaction',
  'gesture',
  'drag-drop',
  'hover',
  'focus-state',
  'keyboard-nav',
  'shortcut',
  'onboarding',
  'usability',
  'user-flow',
  'wireframe',
  'mockup',
  'design-system',
  'design-token',
  'figma',
  'material-design',
  'dark-mode',
  'light-mode',
  'theme',
  'typography',
  'color-scheme',
  'contrast',
  'spacing',
  'elevation',
  'motion',
  'easing',
  'spring',
  'haptics',
  'feedback',
  'affordance',
  'discoverability',
  'error-message',
  'loading-state',
  'undo',
  'confirmation',
  'tour',
  'a11y',
  // frontend tech
  'css',
  'html',
  'sass',
  'tailwind',
  'styled-components',
  'css-variables',
  'media-query',
  'container-query',
  'vite',
  'webpack',
  'esbuild',
  'rollup',
  'nextjs',
  'vue',
  'angular',
  'svelte',
  'solid-js',
  'astro',
  'redux',
  'zustand',
  'react-query',
  'hooks',
  'context-api',
  'props',
  'state-management',
  'router',
  'ssr',
  'csr',
  'ssg',
  'hydration',
  'spa',
  'bundle-size',
  'tree-shaking',
  'code-splitting',
  'lazy-loading',
  'service-worker',
  'web-components',
  'shadow-dom',
  'dom',
  'event-listener',
  'intersection-observer',
  'canvas',
  'svg',
  'webgl',
  'three-js',
  'viewport',
  'favicon',
  'meta-tags',
  'open-graph',
  // backend & architecture
  'rest',
  'grpc',
  'rpc',
  'microservices',
  'monolith',
  'serverless',
  'lambda',
  'edge-function',
  'queue',
  'worker',
  'job',
  'cron',
  'scheduler',
  'webhook',
  'middleware',
  'orm',
  'query-builder',
  'transaction',
  'db-index',
  'schema',
  'normalization',
  'replication',
  'sharding',
  'connection-pool',
  'backup',
  'restore',
  'seed-data',
  'fixture-data',
  'pubsub',
  'event-driven',
  'event-sourcing',
  'cqrs',
  'saga',
  'domain-model',
  'ddd',
  'clean-architecture',
  'hexagonal',
  'dependency-injection',
  'singleton',
  'factory',
  'repository-pattern',
  'session-store',
  'multi-tenant',
  'feature-toggle',
  'idempotency',
  'concurrency',
  'parallelism',
  'race-condition',
  'deadlock',
  'async',
  'await',
  'streaming',
  'batch',
  'etl',
  'data-pipeline',
  'rate-limit',
  'throttling',
  'retry',
  'backoff',
  'timeout',
  'circuit-breaker',
  'health-check',
  'graceful-shutdown',
  'hot-reload',
  'scalability',
  'availability',
  'resilience',
  'failover',
  // data stores & infra tech
  'postgres',
  'mysql',
  'sqlite',
  'mongodb',
  'redis',
  'elasticsearch',
  'kafka',
  'rabbitmq',
  's3',
  'cdn',
  'load-balancer',
  'reverse-proxy',
  'nginx',
  'apache',
  'dns',
  'ssl',
  'vps',
  'bare-metal',
  'vm',
  'wasm',
  // security
  'auth',
  'oauth',
  'oidc',
  'jwt',
  'session-token',
  'cookie',
  'csrf',
  'xss',
  'sql-injection',
  'path-traversal',
  'encryption',
  'hashing',
  'argon2',
  'tls',
  'https',
  'cors',
  'csp',
  'secrets',
  'env-vars',
  'permissions',
  'rbac',
  'acl',
  'mfa',
  'sso',
  'audit-log',
  'gdpr',
  'privacy',
  'pen-test',
  'vulnerability',
  'sanitization',
  'input-validation',
  'allowlist',
  'sandbox',
  'supply-chain',
  'cve',
  // testing & qa
  'tdd',
  'bdd',
  'mock',
  'stub',
  'spy',
  'test-fixture',
  'snapshot-test',
  'smoke-test',
  'load-test',
  'stress-test',
  'fuzzing',
  'coverage',
  'regression-test',
  'acceptance-test',
  'contract-test',
  'qa',
  'flaky-test',
  'playwright',
  'cypress',
  'vitest',
  'jest',
  'pytest',
  'assertion',
  'test-data',
  'edge-case',
  // devops & cloud
  'kubernetes',
  'helm',
  'terraform',
  'ansible',
  'aws',
  'azure',
  'gcp',
  'vercel',
  'netlify',
  'cloudflare',
  'github-actions',
  'gitlab-ci',
  'jenkins',
  'pipeline',
  'artifact',
  'container',
  'image',
  'registry',
  'rollback',
  'blue-green',
  'canary',
  'feature-flag',
  'observability',
  'tracing',
  'metrics',
  'alerting',
  'incident',
  'postmortem',
  'on-call',
  'sre',
  'iac',
  'provisioning',
  'autoscaling',
  'cost-optimization',
  'sandbox-env',
  'staging',
  'production',
  'dotenv',
  'systemd',
  'pm2',
  // ai & data
  'ai',
  'llm',
  'prompt-engineering',
  'embedding',
  'rag',
  'fine-tuning',
  'machine-learning',
  'model',
  'inference',
  'dataset',
  'nlp',
  'computer-vision',
  'anthropic',
  'claude',
  'openai',
  'agent',
  'chatbot',
  'vector-db',
  'tokenization',
  'classification',
  'recommendation',
  'speech-to-text',
  'text-to-speech',
  'ocr',
  'sentiment',
  'hallucination',
  'context-window',
  'system-prompt',
  'few-shot',
  'mcp',
  // mobile & platforms
  'ios',
  'android',
  'react-native',
  'flutter',
  'swift',
  'kotlin',
  'app-store',
  'play-store',
  'push-notification',
  'deep-link',
  'offline-first',
  'sync',
  'biometrics',
  'widget',
  'tablet',
  'watch',
  'electron',
  'tauri',
  'browser-extension',
  'cross-platform',
  // process & collaboration
  'agile',
  'scrum',
  'kanban',
  'sprint',
  'backlog',
  'estimation',
  'retrospective',
  'standup',
  'code-review',
  'pair-programming',
  'adr',
  'rfc',
  'changelog',
  'versioning',
  'semver',
  'git',
  'branching',
  'merge',
  'rebase',
  'cherry-pick',
  'monorepo',
  'submodule',
  'open-source',
  'license',
  'roadmap',
  'milestone',
  'issue-tracker',
  'pull-request',
  'conventional-commits',
  'pre-commit',
  // code quality & craft
  'readability',
  'maintainability',
  'modularity',
  'dry',
  'solid',
  'kiss',
  'yagni',
  'design-pattern',
  'anti-pattern',
  'coupling',
  'cohesion',
  'naming',
  'dead-code',
  'complexity',
  'cyclomatic',
  'linting',
  'formatting',
  'prettier',
  'eslint',
  'type-safety',
  'null-safety',
  'immutability',
  'side-effects',
  'pure-function',
  'abstraction',
  'encapsulation',
  'inheritance',
  'composition',
  'generics',
  'api-design',
  // general engineering
  'cli',
  'tui',
  'sdk',
  'plugin',
  'extension',
  'integration',
  'third-party',
  'email',
  'smtp',
  'pdf',
  'export-data',
  'import-data',
  'upload',
  'download',
  'clipboard',
  'file-system',
  'timezone',
  'date-time',
  'unicode',
  'encoding',
  'utf-8',
  'compression',
  'parsing',
  'serialization',
  'json',
  'yaml',
  'xml',
  'csv',
  'regex',
  'algorithm',
  'data-structure',
  'recursion',
  'memoization',
  'binary',
  'bitwise',
  'uuid',
  'slug',
  'search-index',
  'fuzzy-search',
  'geolocation',
  'barcode',
  'qr-code',
  'payments',
  'stripe',
  'invoice',
  'subscription',
  'cron-expression',
  'feature-request',
  'proof-of-concept',
  'benchmark',
  'profiling',
  'memory-leak',
  'garbage-collection',
  'stack-trace',
  'debugging',
  'breakpoint',
  'telemetry',
  // languages
  'javascript',
  'java',
  'c',
  'cpp',
  'csharp',
  'php',
  'ruby',
  'scala',
  'haskell',
  'lua',
  'perl',
  'r-lang',
  'matlab',
  'dart',
  'elixir',
  'erlang',
  'clojure',
  'zig',
  'nim',
  'assembly',
  'fortran',
  'cobol',
  'groovy',
  'objective-c',
  'shell-script',
  'bash',
  'zsh',
  'powershell',
  'vbscript',
  'solidity',
  // frameworks & libraries
  'django',
  'flask',
  'fastapi',
  'spring-boot',
  'laravel',
  'symfony',
  'rails',
  'express',
  'nestjs',
  'fastify',
  'dotnet',
  'blazor',
  'qt',
  'gtk',
  'pyside',
  'jquery',
  'bootstrap',
  'bulma',
  'material-ui',
  'chakra',
  'shadcn',
  'radix',
  'framer-motion',
  'gsap',
  'd3',
  'chartjs',
  'leaflet',
  'mapbox',
  'socket-io',
  'axios',
  'lodash',
  'moment',
  'dayjs',
  'numpy',
  'pandas',
  'scikit-learn',
  'pytorch',
  'tensorflow',
  'keras',
  'langchain',
  'sqlalchemy',
  'prisma',
  'drizzle',
  'knex',
  // protocols & networking
  'http',
  'http2',
  'http3',
  'tcp',
  'udp',
  'quic',
  'mqtt',
  'amqp',
  'ftp',
  'sftp',
  'ssh',
  'imap',
  'pop3',
  'telnet',
  'ipv4',
  'ipv6',
  'nat',
  'vpn',
  'proxy',
  'socket',
  'port',
  'firewall',
  'packet',
  'latency',
  'bandwidth',
  'throughput',
  'handshake',
  'keep-alive',
  'long-polling',
  'sse',
  'multiplexing',
  'network',
  'subnet',
  'routing',
  'peer-to-peer',
  'webrtc',
  'sip',
  'ntp',
  'icmp',
  'arp',
  // systems & low-level
  'compiler',
  'interpreter',
  'runtime',
  'jit',
  'bytecode',
  'linker',
  'assembler',
  'kernel',
  'driver',
  'syscall',
  'process',
  'thread',
  'mutex',
  'semaphore',
  'lock',
  'atomic',
  'scheduling',
  'interrupt',
  'memory-management',
  'heap',
  'stack',
  'pointer',
  'buffer',
  'buffer-overflow',
  'endianness',
  'file-descriptor',
  'signal-handling',
  'ipc',
  'shared-memory',
  'hypervisor',
  'bootloader',
  'cross-compile',
  'arm64',
  'x86',
  'risc-v',
  'simd',
  'gpu',
  'cuda',
  'multithreading',
  // build & package tooling
  'make',
  'cmake',
  'gradle',
  'maven',
  'bazel',
  'npm',
  'yarn',
  'pnpm',
  'pip',
  'uv-python',
  'poetry',
  'cargo',
  'composer',
  'nuget',
  'homebrew',
  'apt',
  'snap',
  'node-modules',
  'lockfile',
  'peer-dependency',
  'transpile',
  'minify',
  'source-map',
  'polyfill',
  'shim',
  'vendor',
  'monkey-patch',
  'hot-module-reload',
  // editors & dev tools
  'vscode',
  'vim',
  'neovim',
  'emacs',
  'jetbrains',
  'intellij',
  'xcode',
  'android-studio',
  'tmux',
  'iterm',
  'terminal',
  'shell',
  'dotfiles',
  'snippet',
  'emmet',
  'language-server',
  'lsp',
  'debugger-tool',
  'devtools',
  'postman',
  'insomnia',
  'curl',
  'wget',
  'jq',
  'grep',
  'sed',
  'awk',
  'diff',
  'patch',
  // hardware & iot
  'embedded',
  'firmware',
  'iot',
  'raspberry-pi',
  'arduino',
  'esp32',
  'microcontroller',
  'gpio',
  'pwm',
  'i2c',
  'spi',
  'uart',
  'serial',
  'sensor',
  'actuator',
  'relay',
  'led',
  'display',
  'touchscreen',
  'bluetooth',
  'ble',
  'wifi',
  'zigbee',
  'lora',
  'rfid',
  'nfc',
  'usb',
  'hdmi',
  'battery',
  'power-management',
  'robotics',
  'drone',
  '3d-printing',
  'cnc',
  'home-automation',
  'smart-home',
  'hue',
  'mqtt-broker',
  // game development
  'game-dev',
  'unity',
  'unreal',
  'godot',
  'game-engine',
  'physics-engine',
  'collision',
  'sprite',
  'shader',
  'texture',
  'mesh',
  'rigging',
  'particle',
  'raycast',
  'pathfinding',
  'game-loop',
  'fps',
  'multiplayer',
  'matchmaking',
  'leaderboard',
  'achievement',
  'level-design',
  'procedural-generation',
  'pixel-art',
  'tilemap',
  'isometric',
  'vr',
  'ar',
  'xr',
  // audio & video
  'audio',
  'video',
  'codec',
  'ffmpeg',
  'streaming-media',
  'hls',
  'dash-streaming',
  'transcoding',
  'waveform',
  'fft',
  'dsp',
  'midi',
  'synthesizer',
  'sample-rate',
  'microphone',
  'speaker',
  'volume',
  'equalizer',
  'bpm',
  'beat-detection',
  'subtitle',
  'thumbnail',
  'image-processing',
  'exif',
  'webcam',
  // docs & communication
  'readme',
  'tutorial',
  'guide',
  'how-to',
  'faq',
  'api-docs',
  'swagger',
  'openapi',
  'jsdoc',
  'docstring',
  'diagram',
  'flowchart',
  'mermaid',
  'uml',
  'sequence-diagram',
  'architecture-diagram',
  'runbook',
  'knowledge-base',
  'wiki',
  'release-notes',
  'spec',
  'requirements',
  'user-story',
  'glossary',
  // business & product
  'saas',
  'b2b',
  'b2c',
  'crm',
  'erp',
  'cms',
  'e-commerce',
  'checkout',
  'cart',
  'pricing',
  'billing',
  'freemium',
  'trial',
  'onboarding-flow',
  'retention',
  'churn',
  'conversion',
  'funnel',
  'ab-testing',
  'growth',
  'marketing',
  'newsletter',
  'landing-page',
  'waitlist',
  'beta',
  'launch',
  'mvp-scope',
  'kpi',
  'okr',
  'stakeholder',
  'compliance',
  'sla',
  'support',
  'ticketing',
  'feedback-loop',
  // reliability & operations
  'uptime',
  'downtime',
  'outage',
  'degradation',
  'disaster-recovery',
  'rto',
  'rpo',
  'chaos-engineering',
  'capacity-planning',
  'resource-limit',
  'oom',
  'cpu-usage',
  'memory-usage',
  'disk-usage',
  'io-bound',
  'cpu-bound',
  'bottleneck',
  'hot-path',
  'cold-start',
  'warmup',
  'cache-invalidation',
  'ttl',
  'eviction',
  'watchdog',
  'heartbeat',
  'self-healing',
  'janitor',
  'retention-policy',
  'log-rotation',
  'archival',
  // data engineering & analytics
  'data-warehouse',
  'data-lake',
  'olap',
  'oltp',
  'bi',
  'reporting',
  'aggregation',
  'materialized-view',
  'partitioning',
  'time-series',
  'geospatial',
  'full-text-search',
  'ranking',
  'deduplication',
  'data-quality',
  'data-migration',
  'schema-evolution',
  'backfill',
  'snapshot',
  'delta',
  'upsert',
  'bulk-insert',
  'pagination-cursor',
  'n-plus-one',
  'query-plan',
  'explain',
  'vacuum',
  'wal',
  // auth & identity
  'login',
  'logout',
  'signup',
  'registration',
  'password',
  'password-reset',
  'magic-link',
  'passkey',
  'webauthn',
  'captcha',
  'rate-limiting-auth',
  'account-lockout',
  'identity-provider',
  'ldap',
  'saml',
  'scim',
  'token-refresh',
  'access-token',
  'refresh-token',
  'impersonation',
  'user-profile',
  'avatar-upload',
  // ui text & content
  'copywriting',
  'microcopy',
  'tone-of-voice',
  'truncation',
  'ellipsis',
  'line-clamp',
  'word-break',
  'hyphenation',
  'rtl',
  'ltr',
  'pluralization',
  'number-format',
  'currency-format',
  'date-format',
  'relative-time',
  'emoji',
  'markdown-rendering',
  'syntax-highlighting',
  'code-block',
  'rich-text',
  // apis & integration
  'sdk-design',
  'api-versioning',
  'deprecation',
  'backward-compatibility',
  'forward-compatibility',
  'pagination-api',
  'filtering-api',
  'sorting-api',
  'batch-api',
  'bulk-api',
  'graphql-schema',
  'resolver',
  'mutation',
  'subscription-api',
  'introspection',
  'api-gateway',
  'service-mesh',
  'etag',
  'conditional-request',
  'content-negotiation',
  'hateoas',
  'callback-url',
  'polling',
  'zapier',
  'ifttt',
  'slack-integration',
  'github-api',
  'google-api',
  'stripe-api',
  'twilio',
  // misc broad
  'prototype-app',
  'greenfield',
  'brownfield',
  'legacy',
  'rewrite',
  'fork',
  'upstream',
  'downstream',
  'vendor-lock-in',
  'interoperability',
  'portability',
  'determinism',
  'reproducibility',
  'idempotent-script',
  'dry-run',
  'rollout',
  'kill-switch',
  'circuit',
  'graceful-degradation',
  'progressive-enhancement',
  'feature-detection',
  'user-agent',
  'fingerprinting',
  'session-replay',
  'heatmap-analytics',
  'crash-reporting',
  'sentry',
  'error-budget',
  'tech-radar',
  'spike-solution',
]
